tads/Grafos
nicoandreoli2000/obligatorio-a2 pull request #7
Opened 2022-04-28 14:38 UTC by SpiderFuk

tads/Grafo completo
tads/List iterator implementado
tads/Pair fst y snd implementado

2022-04-30 21:48 UTC, nicoandreoli2000 requested changes

2022-04-30 21:48 UTC, nicoandreoli2000 commented on tads/List.java
> +  }
Fijate si siguen pasando todos los tests antes de mergear esto, yo no hice el `Iterator` porque me trajo mas problemas

2022-04-30 21:48 UTC, nicoandreoli2000 commented on tads/List.java
> +    // }
Borra este comment nomas

2022-04-30 21:48 UTC, nicoandreoli2000 commented on tads/List.java
> +    // }
Idem aca

2022-04-30 21:48 UTC, nicoandreoli2000 commented on tads/Grafo.java
> +     */
Te animas a poner esto en el Docs asi no queda aca en el codigo?

2022-05-01 03:42 UTC, SpiderFuk commented on tads/List.java
> +  }
Los test siguen funcionando si, solo le di uso al iterator para dejar mas prolijo el codigo y tambien por que originalmente iba a utilizar las listas para grafo y necesitaba el iterator, asi que los cambios a listas se pueden descartar

2022-05-06 01:32 UTC, nicoandreoli2000 commented on tads/Grafo.java
> +        // }
borrar comments

2022-05-06 03:31 UTC, nicoandreoli2000 approved these changes

2022-05-06 03:31 UTC, merged